version: "3.8"
services:
  dev:
    build:
      context: .
    container_name: i2tf3-dev
    working_dir: /opt/app
    tty: true
    volumes:
      - .:/opt/app

  elasticsearch:
    image: elasticsearch:8.1.2
    container_name: i2tf3-elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:8.1.2
    container_name: i2tf3-kibana
    ports:
        - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
